# Generated by Django 5.1 on 2024-08-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('email', models.EmailField(max_length=255, verbose_name='返信用アドレス')),
                ('body', models.TextField(verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('body', models.TextField(verbose_name='本文')),
                ('is_published', models.BooleanField(default=True, verbose_name='公開フラグ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
        ),
    ]
