# Generated by Django 5.0.8 on 2024-09-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content1',
            field=models.TextField(blank=True, null=True, verbose_name='内容1'),
        ),
        migrations.AddField(
            model_name='news',
            name='content2',
            field=models.TextField(blank=True, null=True, verbose_name='内容2'),
        ),
        migrations.AddField(
            model_name='news',
            name='content3',
            field=models.TextField(blank=True, null=True, verbose_name='内容3'),
        ),
        migrations.AddField(
            model_name='news',
            name='item1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='項目1'),
        ),
        migrations.AddField(
            model_name='news',
            name='item2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='項目2'),
        ),
        migrations.AddField(
            model_name='news',
            name='item3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='項目3'),
        ),
    ]
